// <auto-generated />
using System;
using APIWebTinTuc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIWebTinTuc.Migrations
{
    [DbContext(typeof(MyDBcontext))]
    partial class MyDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIWebTinTuc.Data.DataBaiViet", b =>
                {
                    b.Property<Guid>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenBaiViet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheLoai")
                        .HasColumnType("int");

                    b.HasKey("MaBaiViet");

                    b.HasIndex("TheLoai");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("APIWebTinTuc.Data.LoaiBaiViet", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Maloai");

                    b.ToTable("LoaiBV");
                });

            modelBuilder.Entity("APIWebTinTuc.Data.DataBaiViet", b =>
                {
                    b.HasOne("APIWebTinTuc.Data.LoaiBaiViet", "Loai")
                        .WithMany("dataBV")
                        .HasForeignKey("TheLoai");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("APIWebTinTuc.Data.LoaiBaiViet", b =>
                {
                    b.Navigation("dataBV");
                });
#pragma warning restore 612, 618
        }
    }
}
